name: JParryPhotography
favicon: null
layout_spectrum: 0.055482310708612204
typography_spectrum: 0.8987565615680069
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7403799365274608
  lightness: 0.06272946111857891
  saturation: 0.4513060082681477
  rhythmicContrast: 0.5117516324389726
purpose: []
