name: JParryPhotography
favicon: null
layout_spectrum: 0.40678
typography_spectrum: 0.58714
title: Photography by Joseph Parry
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ead8c4'
    - '#36312f'
    - '#e3bb81'
    - '#997552'
    - '#735742'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
