name: JParryPhotography
favicon: null
layout_spectrum: 0.15449326043017209
typography_spectrum: 0.012968309689313173
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7645292058587074
  lightness: 0.19390924670733511
  saturation: 0.5066908055450767
  rhythmicContrast: 0.6789133362472057
purpose: []
