name: JParryPhotography
favicon: null
layout_spectrum: 0.64059
typography_spectrum: 0.58714
title: Photography by Joseph Parry
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ead8c4'
    - '#36312f'
    - '#e3bb81'
    - '#997552'
    - '#735742'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
