name: JParryPhotography
favicon: null
layout_spectrum: 0.0012426048051565886
typography_spectrum: 0.5915155550464988
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6069817231036723
  lightness: 0.49894919409416616
  saturation: 0.4303914615884423
  rhythmicContrast: 0.644706460647285
purpose: []
